Seo
stackbit-themes/starter-nextjs-contentful-theme pull request #6
Opened 2022-02-04 00:15 UTC by JugglerX

2022-02-06 18:42 UTC, smnh requested changes

2022-02-06 18:42 UTC, smnh commented on sourcebit.js
> +                    const pageObjects = objects.filter((page) => ['PageLayout', 'PostFeedLayout', 'PostLayout'].includes(page?.__metadata.modelName));
Is there a reason why `?` was added to a `page` object (`page?.__metadata`)?
It looks like a defensive coding over a possible hidden bug. The objects should never come empty.

2022-02-06 18:42 UTC, smnh commented on src/utils/data-utils.js
> +    return objects.filter((object) => object?.__metadata?.modelName === 'PostLayout');
Same here, was there an exception that told you that `object` is undefined that made you put the `?` after `object`? You might found a bug and by adding `?` now hiding it.

2022-02-06 18:42 UTC, smnh commented on sourcebit.js
> +                    site.env = setEnvironmentVariables();
maybe it is better to destruct the `env` to specific variables and name them by their names, like `domain`, etc.
```
site = {
  ...site,
  ...(setEnvironmentVariables())
}
```
Where `setEnvironmentVariables` returns object with `{ domain: ... }`

2022-02-06 18:42 UTC, smnh commented on src/utils/seo-utils.js
> +        ...(seoGenerateOgImage(page, site) && { 'og:image': seoGenerateOgImage(page, site) }),
Here the method should be called once, and its result should be used in condition.
It is not about performance, or being concerned that the method runs twice. It is about the code quality of our public repos.

```js
const seoTitle = seoGenerateTitle(page, site);

pageMetaTags = {
   ...pageMetaTags,
   ...(seoTitle && { 'og:title': seoTitle }),
```

Or even better, make the function return an object with `og:title` or an empty object if no title, this will reduce the code to this:
```js
pageMetaTags = {
   ...pageMetaTags,
   ...(seoGenerateTitle(page, site)),
```

2022-02-07 03:40 UTC, JugglerX commented on sourcebit.js
> +                    const pageObjects = objects.filter((page) => ['PageLayout', 'PostFeedLayout', 'PostLayout'].includes(page?.__metadata.modelName));
Yes I got stuck not able to load the site because `page` was null. I've never seen this before, only with Contentful theme. It felt like something to do with modifying the models in Contentful while running locally.

But you are correct. This is likely just hiding another bug which I wasn't able to fully reproduce. 

I'll remove the `?`

2022-02-07 03:50 UTC, JugglerX commented on sourcebit.js
> +                    site.env = setEnvironmentVariables();
Having the environment variable name match the variable name in the codebase can make things clearer. Ie if I do `export URL="www.google.com"` and then i see `site.env.URL` in the code it's super clear what the connection is. 

This function is intended to take any and all env variables and make them available on site. 

Nesting the values under site.env makes it clear they are env variables, which is helpful.

2022-02-07 03:57 UTC, JugglerX commented on src/utils/seo-utils.js
> +        ...(seoGenerateOgImage(page, site) && { 'og:image': seoGenerateOgImage(page, site) }),
Good improvement. I was not happy with this code at all, it was very ugly.

I do like how elegant option 2 is `...(seoGenerateTitle(page, site))` but I worry returning an object (or empty object) is worse then returning string or null. Also I call seoGenerateTitle in several places to populate `<title>` and `<meta property="og:title"` so returning `og:title` in the object makes it less flexible, for `<title>` i just need the actual title string.

2022-02-07 10:28 UTC, smnh commented on sourcebit.js
> +                    const pageObjects = objects.filter((page) => ['PageLayout', 'PostFeedLayout', 'PostLayout'].includes(page?.__metadata.modelName));
Yep. We need to identify the source for the page being `null`. That might be a serious bug, maybe in sourcebit-source-contentful plugin.

2022-02-07 10:30 UTC, smnh commented on sourcebit.js
> +                    site.env = setEnvironmentVariables();
Ok, I see the point in that.

2022-02-07 10:32 UTC, smnh approved these changes

2022-02-07 23:48 UTC, merged